import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * The six top-level categories are fixed and shared across all five
 * warehouse-systems documentation sites, in this order:
 * Overview, Business Context, Domain-Driven Design, API Reference,
 * Ecosystem, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Business Context',
      link: {type: 'doc', id: 'business-context/domain-vision'},
      items: [
        'business-context/ubiquitous-language',
        'business-context/chaotic-storage',
        'business-context/revocable-reservations',
        'business-context/usable-inventory',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/subdomain-classification'},
      items: [
        'ddd/aggregates-and-invariants',
        'ddd/domain-events',
        'ddd/use-cases',
        'ddd/context-relationships',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar, 'api-reference/events'],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/context-map'},
      items: ['ecosystem/integration'],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      collapsed: false,
      items: ['mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Analytics (Data Product)',
      collapsed: false,
      items: ['analytics/inventory-flow-accuracy-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-chaotic-storage-over-fixed-slotting',
        'adr/0003-revocable-reservations',
        'adr/0004-kafka-integration-events',
        'adr/0005-rfc-7807-problem-details',
        'adr/0006-arch-go-fitness-tests',
        'adr/0007-godog-bdd-acceptance-tests',
        'adr/0008-mcp-inbound-adapter',
        'adr/0009-product-classification-as-sku-master-data',
        'adr/0010-dot-hazard-class-and-same-bin-segregation',
        'adr/0011-analytical-data-product',
      ],
    },
  ],
};

export default sidebars;
